import BackgroundLayout from "./components/Background/BackgroundLayout";
import Cursor from "./components/Cursor";
import NavigationBar from "./components/NavigationBar";
import "./globals.scss";

export const metadata = {
  title: "Rhysin Dev Portfolio",
  description: "Generated by create Next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="isolate">
        <div className="w-screen h-screen relative overflow-hidden">
          <div className="absolute w-[150%] h-full  top-0 bottom-0 z-[-1] ">
            <BackgroundLayout />
          </div>
          <NavigationBar></NavigationBar>

          <div id="container" className="w-screen h-[calc(100vh-3.5rem)] ">
            {children}
          </div>
        </div>
        <Cursor/>
      </body>
    </html>
  );
}
